"""Alter students table

Revision ID: 7b8e2f529afc
Revises: 549c97ba5014
Create Date: 2021-12-24 10:26:55.129795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8e2f529afc'
down_revision = '549c97ba5014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_meta', sa.Column('value', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'student_meta', ['value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_meta', type_='unique')
    op.drop_column('student_meta', 'value')
    # ### end Alembic commands ###
